Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def myexp(x):
    return np.exp(x)
myexp(Dual(3,1))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;31mAttributeError[0m: 'Dual' object has no attribute 'exp'

The above exception was the direct cause of the following exception:

[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[11], line 3[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mmyexp[39m(x):
[1;32m      2[0m     [38;5;28;01mreturn[39;00m np[38;5;241m.[39mexp(x)
[0;32m----> 3[0m [43mmyexp[49m[43m([49m[43mDual[49m[43m([49m[38;5;241;43m3[39;49m[43m,[49m[38;5;241;43m1[39;49m[43m)[49m[43m)[49m

Cell [0;32mIn[11], line 2[0m, in [0;36mmyexp[0;34m(x)[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mmyexp[39m(x):
[0;32m----> 2[0m     [38;5;28;01mreturn[39;00m [43mnp[49m[38;5;241;43m.[39;49m[43mexp[49m[43m([49m[43mx[49m[43m)[49m

[0;31mTypeError[0m: loop of ufunc does not support argument 0 of type Dual which has no callable exp method

